aliases:
  - &attach-workspace
    attach_workspace:
      at: ~/react-native-url-polyfill

defaults: &defaults
  executor: rn/linux_js
  working_directory: ~/react-native-url-polyfill

# ios: &ios
#   macos:
#     xcode: 11

# android: &android
#   docker:
#     - image: circleci/android:api-28-node
#   environment:
#     JAVA_TOOL_OPTIONS: '-Xmx1536m'
#     GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2'

orbs:
  rn: react-native-community/react-native@4.4.2
version: 2.1
# commands:
#   test-detox-ios:
#     steps:
#       - *attach-workspace
#       - *restore-cache-detox
#       - run:
#           name: Yarn version
#           command: yarn -v
#       - run:
#           name: Yarn Install
#           command: |
#             yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
#       - run:
#           name: Install Detox
#           command: |
#             brew update
#             brew tap wix/brew
#             brew install applesimutils
#             yarn global add detox-cli
#       - run:
#           name: Clean Detox
#           command: |
#             detox clean-framework-cache && detox build-framework-cache
#       - run:
#           name: Install Pods
#           command: |
#             curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
#             cd ios && pod install --repo-update
#       - run:
#           name: Run Detox on iOS
#           command: yarn e2e:ios
#       - *save-cache-detox
#   test-hermes:
#     steps:
#       - *attach-workspace
#       - *restore-android-build-cache
#       - run:
#           name: Yarn version
#           command: yarn -v
#       - run:
#           name: Yarn Install
#           command: |
#             yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
#       - run:
#           name: Enable Hermes
#           command: sed -i "s/enableHermes:\sfalse/enableHermes:\ true/g" android/app/build.gradle
#       - run:
#           name: Build APK
#           command: cd android && ./gradlew assembleRelease
#       - *save-android-build-cache

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - rn/yarn_install
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - *attach-workspace
      - run:
          name: Lint
          command: yarn lint
  test-js:
    <<: *defaults
    steps:
      - *attach-workspace
      - run:
          name: Run Jest
          command: yarn test
  # rn-0-60-test-ios:
  #   <<: *ios
  #   working_directory: ~/react-native-url-polyfill/detox/rn-0.60
  #   steps:
  #     - test-detox-ios
  # rn-0-61-test-ios:
  #   <<: *ios
  #   working_directory: ~/react-native-url-polyfill/detox/rn-0.61
  #   steps:
  #     - test-detox-ios
  # rn-0-61-test-hermes:
  #   <<: *android
  #   working_directory: ~/react-native-url-polyfill/detox/rn-0.61
  #   steps:
  #     - test-hermes
  # rn-0-62-test-ios:
  #   <<: *ios
  #   working_directory: ~/react-native-url-polyfill/detox/rn-0.62
  #   steps:
  #     - test-detox-ios
  # rn-0-62-test-hermes:
  #   <<: *android
  #   working_directory: ~/react-native-url-polyfill/detox/rn-0.62
  #   steps:
  #     - test-hermes

workflows:
  tests:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test-js:
          requires:
            - checkout
      - rn/ios_build_and_test:
          name: rn-0-62-test-ios
          workspace_root: ~/react-native-url-polyfill/detox/rn-0.62
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: iPhone 11 Pro
          project_path: ios/Detox.xcworkspace
          project_type: workspace
          requires:
            - lint
            - test-js
          scheme: Detox
      # - rn-0-60-test-ios:
      #     requires:
      #       - lint
      #       - test-js
      # - rn-0-61-test-ios:
      #     requires:
      #       - lint
      #       - test-js
      # - rn-0-61-test-hermes:
      #     requires:
      #       - lint
      #       - test-js
      # - rn-0-62-test-ios:
      #     requires:
      #       - lint
      #       - test-js
      # - rn-0-62-test-hermes:
      #     requires:
      #       - lint
      #       - test-js
